/*
# Add full application form fields

Adds all missing fields required by the MIHE application form spec across
Personal Details, Emergency Contact, Disability, Previous Qualification,
Credit Transfer / RPL, Purpose of Study, Employment, Visa Information,
GTE & Financial Capacity, Additional Services, Additional Support, and
Student Declaration sections.

All columns are added to the existing `agent_applications` table.
No new tables. No data loss — all additions are additive ALTER TABLE statements.
No RLS changes — existing policies already cover the table.
*/

ALTER TABLE agent_applications
  ADD COLUMN IF NOT EXISTS student_title text,
  ADD COLUMN IF NOT EXISTS student_gender text,
  ADD COLUMN IF NOT EXISTS student_country_of_birth text,
  ADD COLUMN IF NOT EXISTS student_marital_status text,
  ADD COLUMN IF NOT EXISTS student_passport_expiry date,
  ADD COLUMN IF NOT EXISTS student_mobile_number text,
  ADD COLUMN IF NOT EXISTS student_in_australia boolean,
  ADD COLUMN IF NOT EXISTS student_current_location text,
  ADD COLUMN IF NOT EXISTS residential_street_number text,
  ADD COLUMN IF NOT EXISTS residential_street_name text,
  ADD COLUMN IF NOT EXISTS residential_suburb text,
  ADD COLUMN IF NOT EXISTS residential_city text,
  ADD COLUMN IF NOT EXISTS residential_state text,
  ADD COLUMN IF NOT EXISTS residential_country text,
  ADD COLUMN IF NOT EXISTS residential_post_code text,
  ADD COLUMN IF NOT EXISTS postal_same_as_residential boolean,
  ADD COLUMN IF NOT EXISTS postal_street_number text,
  ADD COLUMN IF NOT EXISTS postal_street_name text,
  ADD COLUMN IF NOT EXISTS postal_suburb text,
  ADD COLUMN IF NOT EXISTS postal_city text,
  ADD COLUMN IF NOT EXISTS postal_state text,
  ADD COLUMN IF NOT EXISTS postal_country text,
  ADD COLUMN IF NOT EXISTS postal_post_code text,
  ADD COLUMN IF NOT EXISTS emergency_full_name text,
  ADD COLUMN IF NOT EXISTS emergency_relationship text,
  ADD COLUMN IF NOT EXISTS emergency_address text,
  ADD COLUMN IF NOT EXISTS emergency_mobile text,
  ADD COLUMN IF NOT EXISTS emergency_phone text,
  ADD COLUMN IF NOT EXISTS emergency_email text,
  ADD COLUMN IF NOT EXISTS disability_has boolean,
  ADD COLUMN IF NOT EXISTS disability_details text,
  ADD COLUMN IF NOT EXISTS qualification_level text,
  ADD COLUMN IF NOT EXISTS qualification_name text,
  ADD COLUMN IF NOT EXISTS qualification_year text,
  ADD COLUMN IF NOT EXISTS qualification_institution text,
  ADD COLUMN IF NOT EXISTS qualification_country text,
  ADD COLUMN IF NOT EXISTS qualification_institution_phone text,
  ADD COLUMN IF NOT EXISTS qualification_contact_email text,
  ADD COLUMN IF NOT EXISTS applying_rpl boolean,
  ADD COLUMN IF NOT EXISTS applying_credit_transfer boolean,
  ADD COLUMN IF NOT EXISTS purpose_of_study text,
  ADD COLUMN IF NOT EXISTS purpose_other text,
  ADD COLUMN IF NOT EXISTS employment_status text,
  ADD COLUMN IF NOT EXISTS visa_held boolean,
  ADD COLUMN IF NOT EXISTS visa_previously_held boolean,
  ADD COLUMN IF NOT EXISTS visa_application_status text,
  ADD COLUMN IF NOT EXISTS gte_meets boolean,
  ADD COLUMN IF NOT EXISTS funds_first_year boolean,
  ADD COLUMN IF NOT EXISTS funds_living boolean,
  ADD COLUMN IF NOT EXISTS oshc_arrange boolean,
  ADD COLUMN IF NOT EXISTS airport_pickup boolean,
  ADD COLUMN IF NOT EXISTS additional_support_required boolean,
  ADD COLUMN IF NOT EXISTS additional_support_details text,
  ADD COLUMN IF NOT EXISTS student_decl_1 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_2 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_3 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_4 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_5 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_6 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_7 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_8 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_9 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_10 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_11 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_12 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_13 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS student_decl_name text,
  ADD COLUMN IF NOT EXISTS student_decl_signature text,
  ADD COLUMN IF NOT EXISTS student_decl_date date;